# Autogenerated, do not edit. All changes will be undone.
# Source: https://github.com/pls-rs/pls/blob/main/pkg/brew/pls.template.rb
class Pls < Formula
	desc "Prettier and powerful ls for the pros"
	homepage "https://pls.cli.rs/"
	version "{{ VERSION }}"
	license "GPL-3.0-or-later"

	if OS.mac?
		if Hardware::CPU.arm?
			url "{{ MAC_ARM_URL }}"
			sha256 "{{ MAC_ARM_SHA }}"
		else
			url "{{ MAC_X86_URL }}"
			sha256 "{{ MAC_X86_SHA }}"
		end
	elsif OS.linux?
		if Hardware::CPU.arm?
			url "{{ LINUX_ARM_URL }}"
			sha256 "{{ LINUX_ARM_SHA }}"
		else
			url "{{ LINUX_X86_URL }}"
			sha256 "{{ LINUX_X86_SHA }}"
		end
	end

	def install
		bin.install "pls"
	end

	test do
		assert_match version.to_s, shell_output("#{bin}/pls --version")
	end
end
