set dotenv-load := false
set fallback

# Show all available recipes.
@_default:
    just --list --unsorted

#########
# Setup #
#########

# Install Python dependencies.
install:
    pdm install
    [ -x "$(command -v to-html)" ] || cargo install --git https://github.com/Aloso/to-html --branch main to-html

###########
# Recipes #
###########

# Create the `.env` file from the template file
env:
    cp .env.template .env

# Generate the specified examples file.
gen file:
    pdm run src/examples/{{ file }}.py

# Regenerate all examples.
all:
    just gen hero
    just gen specs
    just gen detail_view
    just gen grid_view
    just gen presentation
    just gen filtering
    just gen sorting
    just gen colors
    just gen paths

# Create a Python shell.
shell:
    pdm run ipython
